# Generated by Django 4.1.5 on 2023-01-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("won", "korean Won"), ("usd", "Dollar")], max_length=10
            ),
        ),
    ]
