# Generated by Django 4.1.5 on 2023-01-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_alter_amenity_options_alter_room_amenities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name": "Amenity", "verbose_name_plural": "Amenities"},
        ),
    ]
