# Generated by Django 4.1.5 on 2023-01-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='House',
        ),
    ]
