# Generated by Django 4.1.5 on 2023-01-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_category_alter_perk_details_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="perk",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="perk",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
