# Generated by Django 4.1.6 on 2023-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0004_alter_experience_category_alter_experience_host_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
