# Generated by Django 4.1.5 on 2023-01-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated",
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
