# Generated by Django 4.1.6 on 2023-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_msgs", "0002_alter_chatting_room_users_alter_message_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatting_room",
            name="name",
            field=models.CharField(
                blank=True, default="Chatting_Room", max_length=10, null=True
            ),
        ),
    ]
