# Generated by Django 4.1.6 on 2023-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_msgs", "0003_chatting_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatting_room",
            name="name",
            field=models.CharField(
                blank=True, default="Chatting_Room", max_length=100, null=True
            ),
        ),
    ]
