# Generated by Django 4.1.6 on 2023-02-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("direct_msgs", "0004_alter_chatting_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="message",
            name="sequence_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="direct_msgs.chatting_room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("room", "sequence_number")},
        ),
    ]
