# Generated by Django 4.1.6 on 2023-02-27 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("direct_msgs", "0005_alter_message_options_message_sequence_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatting_room",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
