# Generated by Django 4.1.6 on 2023-02-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("direct_msgs", "0006_chatting_room_last_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatting_room",
            name="last_activity",
        ),
    ]
