# Generated by Django 4.1.6 on 2023-03-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("direct_msgs", "0007_remove_chatting_room_last_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="user",
            new_name="sender",
        ),
    ]
