# Generated by Django 4.1.6 on 2023-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_msgs", "0008_rename_user_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
